#!/usr/bin/env python3
"""
Update locale translations by calling an LLM API directly.

For each language this script:
  1. Finds the last commit that touched the language's locale.cfg (its "sync
     point" with the English reference).
  2. Computes a key-level delta: keys added to English, keys whose English
     value changed since the sync point, and keys removed from English.
  3. Sends only the delta keys to the model in a single JSON-in/JSON-out
     request (chunked for large deltas). Removed keys are dropped without
     involving the model.
  4. Rebuilds the language file mechanically, mirroring the English file's
     section and key order, so structural validation passes by construction.

Configuration comes from locale-config.json (gitignored; see
locale-config.example.json). By default translation runs through the Claude
Code CLI (`claude -p`), so it is covered by a Claude subscription rather than
per-token API billing. Setting base_url switches to a direct API endpoint
(OpenAI-compatible or Anthropic). Uses only the Python standard library.

Usage: ./update_locales.py [options] [language_code ...]

Options:
  --full            Retranslate every key, not just the delta
  --parallel N      Languages to process concurrently (default from config)
  --context "MSG"   Extra context passed to the model (e.g. what changed and why)
  --model MODEL     Override the configured model
  --base-url URL    Override the configured API base URL
  --dry-run         Show what would be translated without calling the API
"""

import argparse
import concurrent.futures
import json
import os
import re
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
REFERENCE_FILE = PROJECT_ROOT / "locale" / "en" / "locale.cfg"
CONFIG_FILE = PROJECT_ROOT / "locale-config.json"

DEFAULT_CONFIG = {
    "base_url": None,  # None = use the Claude Code CLI; set a URL for direct API access
    "model": "sonnet",
    "api_format": None,  # "claude-code", "openai", or "anthropic"; None = infer
    "api_key_env": None,  # env var holding the API key; None = infer from base_url
    "parallel": 4,
    "chunk_size": 20,  # keys per request for API formats; claude-code sends all at once
    "timeout_seconds": 600,
}

LANGUAGES = {
    "be": "Belarusian",
    "ca": "Catalan",
    "cs": "Czech",
    "de": "German",
    "el": "Greek",
    "es-419": "Spanish (Latin America)",
    "es-ES": "Spanish (Spain)",
    "fi": "Finnish",
    "fr": "French",
    "hu": "Hungarian",
    "it": "Italian",
    "ja": "Japanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "ko": "Korean",
    "lv": "Latvian",
    "nl": "Dutch",
    "no": "Norwegian",
    "pl": "Polish",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    "ro": "Romanian",
    "ru": "Russian",
    "sv": "Swedish",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "vi": "Vietnamese",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
}

# English source for the disclaimer comment required at the top of every
# non-English file (see tests/test_locale.py::test_all_locale_files_ai_disclaimer).
# The URLs must survive translation verbatim.
DISCLAIMER_EN = (
    "This translation was generated by an AI. Corrections are very welcome! "
    "Please add feedback to the mod discussion forum "
    "(https://mods.factorio.com/mod/quality-control/discussion) or as an issue "
    "on the github repo (https://github.com/aarons/factorio-quality-control/issues). "
    "Please forgive me for the mistakes!"
)
DISCLAIMER_URLS = (
    "mods.factorio.com/mod/quality-control/discussion",
    "github.com/aarons/factorio-quality-control/issues",
)
DISCLAIMER_ID = "__disclaimer__"

PLACEHOLDER_RE = re.compile(r"__[A-Za-z0-9-]+__")

print_lock = threading.Lock()


def log(msg):
    with print_lock:
        print(msg, flush=True)


# ---------------------------------------------------------------------------
# Locale file parsing and rendering
# ---------------------------------------------------------------------------

def parse_locale(text):
    """Parse locale.cfg text into {"section/key": value}, preserving order."""
    entries = {}
    section = None
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        section_match = re.match(r"^\[([^\]]+)\]$", stripped)
        if section_match:
            section = section_match.group(1)
            continue
        kv_match = re.match(r"^([^=]+)=(.*)$", line)
        if kv_match and section:
            entries[f"{section}/{kv_match.group(1).strip()}"] = kv_match.group(2)
    return entries


def render_locale(en_text, translations, disclaimer):
    """Rebuild a language file mirroring the English file's exact layout.

    Every section header, blank line, and key from the English file appears in
    the same position; only the values are replaced. This guarantees the
    structural parity the locale tests require.
    """
    out = [f"# {disclaimer}", ""]
    section = None
    for line in en_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        if not stripped:
            out.append("")
            continue
        section_match = re.match(r"^\[([^\]]+)\]$", stripped)
        if section_match:
            section = section_match.group(1)
            out.append(stripped)
            continue
        kv_match = re.match(r"^([^=]+)=(.*)$", line)
        if kv_match and section:
            key = kv_match.group(1).strip()
            out.append(f"{key}={translations[f'{section}/{key}']}")
    # Collapse any accidental double blank lines at the end
    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


def sanitize_value(value):
    """Normalize a model-produced value into a single valid cfg line."""
    value = value.replace("\r", "").replace("\n", "\\n").replace("\t", " ")
    return value.strip()


# ---------------------------------------------------------------------------
# Git helpers for sync-point detection
# ---------------------------------------------------------------------------

def git(*args):
    result = subprocess.run(
        ["git", *args], cwd=PROJECT_ROOT, capture_output=True, text=True
    )
    return result.stdout if result.returncode == 0 else None


def english_at_last_sync(locale_file):
    """English entries as of the last commit touching this language's file.

    Returns None when there is no usable sync point (new or untracked file).
    """
    rel = locale_file.relative_to(PROJECT_ROOT)
    sha = (git("log", "-1", "--format=%H", "--", str(rel)) or "").strip()
    if not sha:
        return None
    old_en = git("show", f"{sha}:locale/en/locale.cfg")
    return parse_locale(old_en) if old_en is not None else None


# ---------------------------------------------------------------------------
# LLM API client (OpenAI-compatible chat completions, or Anthropic messages)
# ---------------------------------------------------------------------------

def load_config():
    config = dict(DEFAULT_CONFIG)
    if CONFIG_FILE.exists():
        text = CONFIG_FILE.read_text(encoding="utf-8")
        # Allow // comment lines so the config can document itself
        text = "\n".join(
            line for line in text.splitlines() if not line.strip().startswith("//")
        )
        config.update(json.loads(text))
    return config


def resolve_api_format(config):
    if config["api_format"]:
        return config["api_format"]
    if not config["base_url"]:
        return "claude-code"
    return "anthropic" if "anthropic" in config["base_url"] else "openai"


def resolve_api_key(config):
    if config["api_key_env"]:
        return os.environ.get(config["api_key_env"], "")
    url = config["base_url"]
    for marker, env in (
        ("openrouter", "OPENROUTER_API_KEY"),
        ("anthropic", "ANTHROPIC_API_KEY"),
        ("openai", "OPENAI_API_KEY"),
    ):
        if marker in url:
            return os.environ.get(env, "")
    return ""  # local servers like LM Studio need no key


def post_json(config, url, headers, body):
    """POST with retry on rate limits and transient errors; returns parsed JSON."""
    headers = {**headers, "Content-Type": "application/json"}
    request = urllib.request.Request(
        url, data=json.dumps(body).encode("utf-8"), headers=headers
    )
    for attempt in range(1, 5):
        try:
            with urllib.request.urlopen(request, timeout=config["timeout_seconds"]) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503, 529) and attempt < 4:
                wait = int(e.headers.get("Retry-After") or 2 ** attempt)
                log(f"  API returned {e.code}, retrying in {wait}s...")
                time.sleep(wait)
                continue
            raise RuntimeError(f"API error {e.code}: {e.read().decode('utf-8', 'replace')[:500]}")
        except (urllib.error.URLError, TimeoutError) as e:
            if attempt < 4:
                time.sleep(2 ** attempt)
                continue
            raise RuntimeError(f"Cannot reach {url}: {e}")


def call_claude_code(config, system_prompt, user_prompt):
    """One headless Claude Code invocation; returns (json_text, None).

    Runs in an empty temp directory so no project context is loaded, and has
    the model Write its JSON to a file — the file comes out as clean JSON with
    no chat commentary to strip. ANTHROPIC_API_KEY is removed from the
    environment so the CLI bills the subscription login, not the API key.
    """
    with tempfile.TemporaryDirectory() as tmp:
        out_path = Path(tmp) / "translations.json"
        prompt = (
            f"{system_prompt}\n\n{user_prompt}\n\n"
            f"Write the JSON object to {out_path} using the Write tool, then stop."
        )
        env = {k: v for k, v in os.environ.items() if k != "ANTHROPIC_API_KEY"}
        try:
            result = subprocess.run(
                ["claude", "-p", "--model", config["model"], "--allowedTools", "Write"],
                input=prompt, cwd=tmp, env=env, capture_output=True, text=True,
                timeout=config["timeout_seconds"],
            )
        except FileNotFoundError:
            raise RuntimeError(
                "claude CLI not found; install Claude Code or set base_url in locale-config.json"
            )
        except subprocess.TimeoutExpired:
            raise ValueError(f"claude timed out after {config['timeout_seconds']}s")
        if not out_path.exists():
            detail = (result.stderr or result.stdout or "").strip()[:300]
            raise ValueError(f"claude produced no output file (exit {result.returncode}): {detail}")
        return out_path.read_text(encoding="utf-8"), None


def call_model(config, system_prompt, user_prompt):
    """Send one request; returns (text, finish_reason)."""
    if resolve_api_format(config) == "claude-code":
        return call_claude_code(config, system_prompt, user_prompt)
    base = config["base_url"].rstrip("/")
    api_key = resolve_api_key(config)

    if resolve_api_format(config) == "anthropic":
        url = f"{base}/v1/messages"
        headers = {"x-api-key": api_key, "anthropic-version": "2023-06-01"}
        body = {
            "model": config["model"],
            "max_tokens": 8192,
            "system": system_prompt,
            "messages": [{"role": "user", "content": user_prompt}],
        }
    else:
        url = f"{base}/chat/completions"
        headers = {"Authorization": f"Bearer {api_key}"} if api_key else {}
        # A single user message rather than system+user: Gemma-family chat
        # templates reject conversations that don't start with a user turn.
        body = {
            "model": config["model"],
            "temperature": 0.3,
            "messages": [
                {"role": "user", "content": f"{system_prompt}\n\n{user_prompt}"},
            ],
        }

    data = post_json(config, url, headers, body)
    if resolve_api_format(config) == "anthropic":
        text = "".join(block.get("text", "") for block in data["content"])
        return text, data.get("stop_reason")
    choice = data["choices"][0]
    return choice["message"]["content"], choice.get("finish_reason")


def extract_json(text):
    """Pull a JSON object out of a model response, tolerating code fences."""
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        raise ValueError(f"No JSON object in response: {text[:200]}")
    return json.loads(text[start : end + 1])


# ---------------------------------------------------------------------------
# Translation
# ---------------------------------------------------------------------------

def build_system_prompt(lang_name, context_msg):
    prompt = f"""You are translating the locale file of "Quality Control", a Factorio mod that gradually upgrades machine quality based on accumulated manufacturing hours.

Translate the given English strings into {lang_name}.

Rules:
- Produce ONLY a JSON object mapping each id to its translation, e.g. {{"mod-setting-name/some-key": "translated text"}}. Every value must be a plain string, never a nested object. Include every id exactly once. No commentary, no code fences.
- The ids are "section/key" paths for your context; translate only the English text given for each.
- Use the terminology from the official Factorio {lang_name} translation for game terms (quality, module, beacon, assembling machine, etc.).
- Preserve placeholders like __1__ and __2__ exactly as written.
- Keep translations concise; these are UI strings.
- If an entry includes "previous_english" and "previous_translation", the English text was revised. Update the previous translation to match the new English text, keeping its established word choices where they still fit."""
    if context_msg:
        prompt += f"\n\nAdditional context from the mod author: {context_msg}"
    return prompt


def build_terminology_examples(en_entries, existing, exclude_ids):
    """Sample existing translations so revised keys keep consistent terminology."""
    examples = {}
    for entry_id, en_value in en_entries.items():
        if entry_id in exclude_ids or entry_id not in existing:
            continue
        if en_value and existing[entry_id] and len(en_value) < 80:
            examples[en_value] = existing[entry_id]
        if len(examples) >= 15:
            break
    return examples


def validate_translation(entry_id, en_value, translated):
    if not translated.strip() and en_value.strip():
        return f"{entry_id}: empty translation"
    en_placeholders = sorted(PLACEHOLDER_RE.findall(en_value))
    tr_placeholders = sorted(PLACEHOLDER_RE.findall(translated))
    if entry_id != DISCLAIMER_ID and en_placeholders != tr_placeholders:
        return f"{entry_id}: placeholders {en_placeholders} became {tr_placeholders}"
    if entry_id == DISCLAIMER_ID and not all(u in translated for u in DISCLAIMER_URLS):
        return f"{entry_id}: disclaimer must keep both URLs verbatim"
    return None


def request_translations(config, system_prompt, entries, terminology):
    """One API call for a batch of entries; returns the parsed JSON response.

    Raises ValueError when the response was truncated or held no JSON, so the
    caller can split the batch and retry with smaller requests.
    """
    payload = {}
    if terminology:
        payload["terminology_examples_english_to_translated"] = terminology
    payload["entries"] = entries
    user_prompt = json.dumps(payload, ensure_ascii=False, indent=1)
    text, finish_reason = call_model(config, system_prompt, user_prompt)
    if finish_reason in ("length", "max_tokens"):
        raise ValueError(f"response truncated (finish_reason={finish_reason})")
    return extract_json(text)


def fallback_value(entry):
    return entry.get("previous_translation") or entry["english"]


def translate_entries(config, lang_name, entries, terminology, context_msg, depth=0):
    """Translate a batch of entries; returns ({id: value}, [warnings]).

    A truncated or unparseable response splits the batch in half and retries
    each half (reasoning-heavy local models choke on large batches). Entries
    failing per-key validation are retried the same way. After 3 levels of
    retries, entries fall back to their previous translation (or English) and
    are reported as warnings.
    """
    if not entries:
        return {}, []

    def recurse_or_fallback(failed, note):
        if depth < 3 and len(failed) > 1:
            halves = list(failed.items())
            mid = (len(halves) + 1) // 2
            results, warnings = {}, []
            for half in (dict(halves[:mid]), dict(halves[mid:])):
                r, w = translate_entries(
                    config, lang_name, half, terminology, context_msg, depth + 1
                )
                results.update(r)
                warnings.extend(w)
            return results, warnings
        return (
            {entry_id: fallback_value(entry) for entry_id, entry in failed.items()},
            [f"{entry_id}: kept fallback value ({note})" for entry_id in failed],
        )

    system_prompt = build_system_prompt(lang_name, context_msg)
    try:
        response = request_translations(config, system_prompt, entries, terminology)
    except (ValueError, json.JSONDecodeError) as e:
        return recurse_or_fallback(entries, str(e))

    results, warnings, failed = {}, [], {}
    last_problem = ""
    for entry_id, entry in entries.items():
        raw = response.get(entry_id)
        if isinstance(raw, str):
            translated = sanitize_value(raw)
            problem = validate_translation(entry_id, entry["english"], translated)
        else:
            # Models sometimes nest the answer ({"translation": ...}); reject
            # anything but a plain string rather than guess which field it's in.
            problem = f"{entry_id}: value must be a plain string, got {type(raw).__name__}"
        if problem is None:
            results[entry_id] = translated
        else:
            failed[entry_id] = entry
            last_problem = problem
    if failed:
        retry_results, retry_warnings = recurse_or_fallback(failed, last_problem)
        results.update(retry_results)
        warnings.extend(retry_warnings)
    return results, warnings


def chunked(items, size):
    items = list(items)
    return [dict(items[i : i + size]) for i in range(0, len(items), size)]


def harmonize_duplicates(final, translated, en_entries):
    """Make identical English texts share one translation everywhere.

    When a run produces variants (e.g. "Peu commun" vs "Peu commune" for
    "Uncommon"), keep the most common one — preferring a translation that
    predates this run — and apply it to every key translated this run.
    Returns notes describing what changed.
    """
    groups = {}
    for entry_id, value in final.items():
        if en_entries[entry_id].strip():
            groups.setdefault(en_entries[entry_id], []).append((entry_id, value))
    notes = []
    for members in groups.values():
        if len({value for _, value in members}) == 1:
            continue
        pre_existing = [v for entry_id, v in members if entry_id not in translated]
        pool = pre_existing or [value for _, value in members]
        canonical = max(set(pool), key=pool.count)
        for entry_id, value in members:
            if entry_id in translated and value != canonical:
                final[entry_id] = translated[entry_id] = canonical
                notes.append(f"{entry_id}: harmonized '{value}' -> '{canonical}'")
    return notes


def find_section_collisions(final, translated, en_entries):
    """Ids translated this run whose value collides within their section.

    Two keys in one section with different English texts must not share a
    translation ("Uncommon" and "Rare" both shown as "Rare" would confuse
    players). Returns only ids we can retranslate, i.e. from this run.
    """
    by_value = {}
    for entry_id, value in final.items():
        if value.strip():
            by_value.setdefault((entry_id.split("/")[0], value), []).append(entry_id)
    collisions = set()
    for ids in by_value.values():
        if len({en_entries[entry_id] for entry_id in ids}) > 1:
            collisions.update(entry_id for entry_id in ids if entry_id in translated)
    return collisions


def process_language(config, lang_code, args, en_text, en_entries):
    """Compute the delta for one language, translate it, and rewrite the file."""
    lang_name = LANGUAGES[lang_code]
    locale_file = PROJECT_ROOT / "locale" / lang_code / "locale.cfg"
    is_new = not locale_file.exists()

    existing = {}
    disclaimer = None
    if not is_new:
        text = locale_file.read_text(encoding="utf-8")
        existing = parse_locale(text)
        first_line = text.splitlines()[0] if text else ""
        if first_line.startswith("#"):
            disclaimer = first_line.lstrip("#").strip()

    # Delta: which keys need the model?
    en_at_sync = None if is_new else english_at_last_sync(locale_file)
    to_translate = {}
    for entry_id, en_value in en_entries.items():
        if not en_value.strip():
            continue  # empty values carry over as empty
        previous = existing.get(entry_id)
        # An existing value identical to English is usually an untranslated
        # fallback from an earlier failed run, so retry it. Legitimately
        # identical words ("Radar") just come back unchanged.
        if args.full or previous is None or previous == en_value:
            to_translate[entry_id] = {"english": en_value}
        elif en_at_sync is not None and entry_id in en_at_sync and en_at_sync[entry_id] != en_value:
            to_translate[entry_id] = {
                "english": en_value,
                "previous_english": en_at_sync[entry_id],
                "previous_translation": previous,
            }
    if disclaimer is None:
        to_translate[DISCLAIMER_ID] = {"english": DISCLAIMER_EN}

    removed = [k for k in existing if k not in en_entries]

    if not to_translate and not removed:
        log(f"  {lang_code} ({lang_name}): up to date")
        return {"lang": lang_code, "status": "up-to-date", "warnings": []}

    summary = f"{len(to_translate)} to translate, {len(removed)} removed"
    if args.dry_run:
        log(f"  {lang_code} ({lang_name}): {summary} [dry run]")
        for entry_id in to_translate:
            log(f"      {entry_id}")
        return {"lang": lang_code, "status": "dry-run", "warnings": []}
    log(f"  {lang_code} ({lang_name}): {summary}")

    terminology = build_terminology_examples(en_entries, existing, set(to_translate))
    translated = {}
    warnings = []
    # Claude Code carries per-invocation overhead (CLI spawn plus its own
    # system prompt), so send everything at once; failures still split.
    chunk_size = (
        len(to_translate)
        if resolve_api_format(config) == "claude-code"
        else config["chunk_size"]
    )
    for chunk in chunked(to_translate.items(), chunk_size):
        chunk_results, chunk_warnings = translate_entries(
            config, lang_name, chunk, terminology, args.context
        )
        translated.update(chunk_results)
        warnings.extend(chunk_warnings)

    if DISCLAIMER_ID in translated:
        disclaimer = translated.pop(DISCLAIMER_ID)

    # Assemble final values: fresh translation > existing > English fallback
    final = {}
    for entry_id, en_value in en_entries.items():
        if not en_value.strip():
            final[entry_id] = ""
        elif entry_id in translated:
            final[entry_id] = translated[entry_id]
        elif entry_id in existing:
            final[entry_id] = existing[entry_id]
        else:
            final[entry_id] = en_value
            warnings.append(f"{entry_id}: missing translation, used English")

    # Deterministic cross-checks for translation consistency
    notes = harmonize_duplicates(final, translated, en_entries)
    collisions = find_section_collisions(final, translated, en_entries)
    if collisions:
        retry_context = (
            f"{args.context}\nA previous attempt translated some of these keys "
            "identically even though their English texts differ. Keys in the same "
            "section with different English texts need distinguishable translations."
        ).strip()
        retry_results, retry_warnings = translate_entries(
            config, lang_name, {i: to_translate[i] for i in sorted(collisions)},
            terminology, retry_context,
        )
        translated.update(retry_results)
        final.update(retry_results)
        warnings.extend(retry_warnings)
        notes += harmonize_duplicates(final, translated, en_entries)
        for entry_id in sorted(find_section_collisions(final, translated, en_entries)):
            warnings.append(f"{entry_id}: still collides with a different English key in its section")
    for note in notes:
        log(f"      note [{lang_code}]: {note}")

    rendered = render_locale(en_text, final, disclaimer)
    if parse_locale(rendered).keys() != en_entries.keys():
        return {
            "lang": lang_code,
            "status": "failed",
            "warnings": warnings + ["rendered file does not mirror English structure; not written"],
        }

    locale_file.parent.mkdir(parents=True, exist_ok=True)
    locale_file.write_text(rendered, encoding="utf-8")

    for warning in warnings:
        log(f"      warning [{lang_code}]: {warning}")
    status = "ok" if not warnings else "ok-with-warnings"
    log(f"  {lang_code} ({lang_name}): done")
    return {"lang": lang_code, "status": status, "warnings": warnings}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Update locale translations via a direct LLM API call per language."
    )
    parser.add_argument("languages", nargs="*", help="Language codes to process (default: all)")
    parser.add_argument("--full", action="store_true", help="Retranslate every key")
    parser.add_argument("--parallel", type=int, default=None)
    parser.add_argument("--context", default="", help="Extra context for the model")
    parser.add_argument("--model", default=None)
    parser.add_argument("--base-url", default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    config = load_config()
    if args.model:
        config["model"] = args.model
    if args.base_url:
        config["base_url"] = args.base_url

    for code in args.languages:
        if code not in LANGUAGES:
            sys.exit(f"Unknown language code '{code}'. Valid: {', '.join(LANGUAGES)}")
    targets = args.languages or list(LANGUAGES)

    if not REFERENCE_FILE.exists():
        sys.exit(f"Reference file not found: {REFERENCE_FILE}")
    en_text = REFERENCE_FILE.read_text(encoding="utf-8")
    en_entries = parse_locale(en_text)

    endpoint = config["base_url"] or "Claude Code CLI"
    log(f"Endpoint: {endpoint}  Model: {config['model']}")
    log(f"Processing {len(targets)} language(s), {len(en_entries)} English keys\n")

    parallel = args.parallel or config["parallel"]
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=parallel) as pool:
        futures = {
            pool.submit(process_language, config, code, args, en_text, en_entries): code
            for code in targets
        }
        for future in concurrent.futures.as_completed(futures):
            code = futures[future]
            try:
                results.append(future.result())
            except Exception as e:
                log(f"  {code}: FAILED — {e}")
                results.append({"lang": code, "status": "failed", "warnings": [str(e)]})

    log("\nSummary")
    log("=======")
    by_status = {}
    for r in sorted(results, key=lambda r: r["lang"]):
        by_status.setdefault(r["status"], []).append(r["lang"])
    for status, langs in sorted(by_status.items()):
        log(f"  {status}: {' '.join(langs)}")

    if not args.dry_run and any(r["status"] != "up-to-date" for r in results):
        log("\nRun ./validate.sh to confirm, and review the changes with git diff.")
    if any(r["status"] == "failed" for r in results):
        sys.exit(1)


if __name__ == "__main__":
    main()
